from application.utils import get_env

class Config:
    APPLICATION_ROOT = get_env('APPLICATION_ROOT')
    SQLALCHEMY_DATABASE_URL = get_env('SQLALCHEMY_DATABASE_URL')
    SQLALCHEMY_TRACK_MODIFICATIONS = get_env('SQLALCHEMY_TRACK_MODIFICATIONS')
    SQLALCHEMY_RECORD_QUERIES = get_env('SQLALCHEMY_RECORD_QUERIES')