"""owners_schema

Revision ID: 74774880e185
Revises: 
Create Date: 2020-11-15 17:16:04.525534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74774880e185'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('raw', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('create_at', sa.String(length=30), nullable=True),
    sa.Column('update_at', sa.String(length=30), nullable=True),
    sa.Column('ip_address', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('raw')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###
