"""empty message

Revision ID: 8b027509fc7b
Revises: 
Create Date: 2020-11-16 17:23:46.575095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b027509fc7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('create_at', sa.String(length=30), nullable=True),
    sa.Column('update_at', sa.String(length=30), nullable=True),
    sa.Column('ip_address', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('row')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stores')
    op.drop_table('owners')
    # ### end Alembic commands ###
