"""empty message

Revision ID: eef8f33173eb
Revises: 
Create Date: 2020-12-01 22:43:20.690476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef8f33173eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('weight_unit', sa.String(length=10), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('available_unit', sa.String(length=10), nullable=False),
    sa.Column('minimal_order', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.BigInteger(), nullable=False),
    sa.Column('sell_price', sa.BigInteger(), nullable=False),
    sa.Column('profit_percentage', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('barcode', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('expired', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_images',
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('row')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_images')
    op.drop_table('products')
    # ### end Alembic commands ###
